// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5j5cTZWfUEWxT7v-UIFH5TVwwHP2Ckz8',
    appId: '1:754296650532:web:48e10a188bd2b8582bd1b1',
    messagingSenderId: '754296650532',
    projectId: 'e-commerce-app-bfe73',
    authDomain: 'e-commerce-app-bfe73.firebaseapp.com',
    databaseURL: 'https://e-commerce-app-bfe73-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-app-bfe73.firebasestorage.app',
    measurementId: 'G-C2J13E8CVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqmK2ecj4s3C5wAQXwX8iISxFZt6EMUrg',
    appId: '1:754296650532:android:054126a98ba8f1582bd1b1',
    messagingSenderId: '754296650532',
    projectId: 'e-commerce-app-bfe73',
    databaseURL: 'https://e-commerce-app-bfe73-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-app-bfe73.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvjnj1Q9MikkZqPwuP5SWyfIkyoGfu6UI',
    appId: '1:754296650532:ios:430b26b1603421792bd1b1',
    messagingSenderId: '754296650532',
    projectId: 'e-commerce-app-bfe73',
    databaseURL: 'https://e-commerce-app-bfe73-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-app-bfe73.firebasestorage.app',
    iosBundleId: 'com.example.authenticationModule',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvjnj1Q9MikkZqPwuP5SWyfIkyoGfu6UI',
    appId: '1:754296650532:ios:430b26b1603421792bd1b1',
    messagingSenderId: '754296650532',
    projectId: 'e-commerce-app-bfe73',
    databaseURL: 'https://e-commerce-app-bfe73-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-app-bfe73.firebasestorage.app',
    iosBundleId: 'com.example.authenticationModule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5j5cTZWfUEWxT7v-UIFH5TVwwHP2Ckz8',
    appId: '1:754296650532:web:8a2dd208fc98f4e22bd1b1',
    messagingSenderId: '754296650532',
    projectId: 'e-commerce-app-bfe73',
    authDomain: 'e-commerce-app-bfe73.firebaseapp.com',
    databaseURL: 'https://e-commerce-app-bfe73-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-app-bfe73.firebasestorage.app',
    measurementId: 'G-VPXWH30YFH',
  );
}
