// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCENHrDV3Vhv8Rpm4cFW6Lk0v1ktOG0iRQ',
    appId: '1:91270722998:web:880eff31ed9f6960e03d17',
    messagingSenderId: '91270722998',
    projectId: 'authentication-app-25933',
    authDomain: 'authentication-app-25933.firebaseapp.com',
    storageBucket: 'authentication-app-25933.firebasestorage.app',
    measurementId: 'G-Z90DXB2XNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsWhVGCkNYKsqu7_LVFx6OTIUde8F48gc',
    appId: '1:91270722998:android:0a487ce553d84c3ce03d17',
    messagingSenderId: '91270722998',
    projectId: 'authentication-app-25933',
    storageBucket: 'authentication-app-25933.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVV6mnRAnbSlMuoP95k16DAxuDhLCYmug',
    appId: '1:91270722998:ios:b71c9d2d49676f65e03d17',
    messagingSenderId: '91270722998',
    projectId: 'authentication-app-25933',
    storageBucket: 'authentication-app-25933.firebasestorage.app',
    iosBundleId: 'com.example.authenticationModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVV6mnRAnbSlMuoP95k16DAxuDhLCYmug',
    appId: '1:91270722998:ios:b71c9d2d49676f65e03d17',
    messagingSenderId: '91270722998',
    projectId: 'authentication-app-25933',
    storageBucket: 'authentication-app-25933.firebasestorage.app',
    iosBundleId: 'com.example.authenticationModule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCENHrDV3Vhv8Rpm4cFW6Lk0v1ktOG0iRQ',
    appId: '1:91270722998:web:1060b319a85806dce03d17',
    messagingSenderId: '91270722998',
    projectId: 'authentication-app-25933',
    authDomain: 'authentication-app-25933.firebaseapp.com',
    storageBucket: 'authentication-app-25933.firebasestorage.app',
    measurementId: 'G-NFBMVWWCHP',
  );
}
